version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-fishmon
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: fishmon
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fishmon-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-fishmon
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - fishmon-network

volumes:
  mysql_data:

networks:
  fishmon-network:
